package AccountSection;


/**
* AccountSection/AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from account.idl
* Monday, February 8, 2016 12:48:26 AM IST
*/

public interface AccountOperations 
{
  void deposit (int amount);
  void withdraw (int amount);
  int getBalance ();
} // interface AccountOperations
