package AccountSection;


/**
* AccountSection/Account.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from account.idl
* Monday, February 8, 2016 12:48:26 AM IST
*/

public interface Account extends AccountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Account
