package AccountSection;

/**
* AccountSection/AccountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from account.idl
* Monday, February 8, 2016 12:48:26 AM IST
*/

public final class AccountHolder implements org.omg.CORBA.portable.Streamable
{
  public AccountSection.Account value = null;

  public AccountHolder ()
  {
  }

  public AccountHolder (AccountSection.Account initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AccountSection.AccountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AccountSection.AccountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AccountSection.AccountHelper.type ();
  }

}
